const productsData = [
  // Auriculares
  {
    id: 1,
    sku: "H2230U",
    name: "Auricular Gamer Plegable USB 7.1 - Negro Havit",
    category: "Auriculares",
    price: 15999,
    description: "Auricular gamer plegable con sonido envolvente USB 7.1 para una experiencia inmersiva",
    image: "productos para testing/H2230U.jpg",
    stock: 20,
  },
  {
    id: 2,
    sku: "H628BT-BG",
    name: "Auricular Inalambrico Bluetooth Plegable - Blanco Havit",
    category: "Auriculares",
    price: 12999,
    description: "Auricular inalámbrico Bluetooth plegable con diseño elegante en color blanco",
    image: "productos para testing/H628BT-BG.jpg",
    stock: 20,
  },
  {
    id: 3,
    sku: "H628BT-BK",
    name: "Auricular Inalambrico Bluetooth Plegable - Negro Havit",
    category: "Auriculares",
    price: 12999,
    description: "Auricular inalámbrico Bluetooth plegable con diseño elegante en color negro",
    image: "productos para testing/H628BT-BK.jpg",
    stock: 20,
  },
  {
    id: 4,
    sku: "H668BT",
    name: "Auricular Bluetooth Vincha - Negro Active Noise Cancelling HIRES Havit",
    category: "Auriculares",
    price: 18999,
    description: "Auricular Bluetooth con cancelación activa de ruido y audio de alta resolución",
    image: "productos para testing/H668BT.jpg",
    stock: 20,
  },
  {
    id: 5,
    sku: "H668BTB",
    name: "Auricular Bluetooth Vincha - Beige Active Noise Cancelling HIRES Havit",
    category: "Auriculares",
    price: 18999,
    description: "Auricular Bluetooth con cancelación activa de ruido y audio de alta resolución en beige",
    image: "productos para testing/H668BTB.jpg",
    stock: 20,
  },
  {
    id: 6,
    sku: "H668BT-P",
    name: "Auricular Bluetooth Over Ear ANC - Púrpura Havit",
    category: "Auriculares",
    price: 18999,
    description: "Auricular Bluetooth over-ear con cancelación activa de ruido en color púrpura",
    image: "productos para testing/H668BT-P.jpg",
    stock: 20,
  },
  {
    id: 7,
    sku: "TW931B",
    name: "Auricular Bluetooth In Ear TWS - Blanco Havit",
    category: "Auriculares",
    price: 8999,
    description: "Auriculares True Wireless Stereo in-ear con estuche de carga en blanco",
    image: "productos para testing/TW931B.jpg",
    stock: 40,
  },
  {
    id: 8,
    sku: "TW931N",
    name: "Auricular Bluetooth In Ear TWS - Negro Havit",
    category: "Auriculares",
    price: 8999,
    description: "Auriculares True Wireless Stereo in-ear con estuche de carga en negro",
    image: "productos para testing/TW931N.jpg",
    stock: 40,
  },
  {
    id: 9,
    sku: "TW969-BK",
    name: "Auricular TWS Negro Havit",
    category: "Auriculares",
    price: 9999,
    description: "Auriculares True Wireless con tecnología avanzada y diseño ergonómico",
    image: "productos para testing/TW969-BK.jpg",
    stock: 40,
  },
  {
    id: 10,
    sku: "TW969-BK-LITE",
    name: "Auricular TWS Negro Lite Havit",
    category: "Auriculares",
    price: 7999,
    description: "Versión lite de auriculares True Wireless con excelente relación calidad-precio",
    image: "productos para testing/TW969-BK-LITE.jpg",
    stock: 40,
  },
  {
    id: 11,
    sku: "H2230D-WG",
    name: "Auricular Gamer Plegable Jack 3.5mm - Blanco / Gris Havit",
    category: "Auriculares",
    price: 11999,
    description: "Auricular gamer plegable con conexión jack 3.5mm en blanco y gris",
    image: "productos para testing/H2230D-WG.jpg",
    stock: 20,
  },
  {
    id: 12,
    sku: "H2230D-BK",
    name: "Auricular Gamer Jack 3.5mm Resistente Negro Havit",
    category: "Auriculares",
    price: 11999,
    description: "Auricular gamer resistente con conexión jack 3.5mm en color negro",
    image: "productos para testing/H2230D-BK.jpg",
    stock: 20,
  },

  // Teclados
  {
    id: 13,
    sku: "KB885L-SP",
    name: "Teclado Mecanico 96% Hotswap Switch Red - Blanco Havit",
    category: "Teclados",
    price: 24999,
    description: "Teclado mecánico 96% con switches intercambiables en caliente, switches red",
    image: "productos para testing/KB885L-SP.jpg",
    stock: 10,
  },
  {
    id: 14,
    sku: "KB899L",
    name: "Teclado Mecanico 97% Hotswap Switch Red - Blanco/Verde Havit",
    category: "Teclados",
    price: 25999,
    description: "Teclado mecánico 97% con switches intercambiables, diseño blanco y verde",
    image: "productos para testing/KB899L.jpg",
    stock: 10,
  },
  {
    id: 15,
    sku: "KB903L-TWH",
    name: "Teclado Mecanico 60% Switch White - Transparente Havit",
    category: "Teclados",
    price: 19999,
    description: "Teclado mecánico compacto 60% con carcasa transparente y switches blancos",
    image: "productos para testing/KB903L-TWH.jpg",
    stock: 10,
  },
  {
    id: 16,
    sku: "KB903L-WH",
    name: "Teclado Mecanico 60% Blanco Havit",
    category: "Teclados",
    price: 18999,
    description: "Teclado mecánico compacto 60% en elegante color blanco",
    image: "productos para testing/KB903L-WH.jpg",
    stock: 10,
  },
  {
    id: 17,
    sku: "KB903L-BK",
    name: "Teclado Mecanico 60% Negro Havit",
    category: "Teclados",
    price: 18999,
    description: "Teclado mecánico compacto 60% en clásico color negro",
    image: "productos para testing/KB903L-BK.jpg",
    stock: 10,
  },

  // Mousepads
  {
    id: 18,
    sku: "MP830",
    name: "Mousepad XXL 90 x 30 x 3 cm - Liso - Negro Havit",
    category: "Mousepads",
    price: 4999,
    description: "Mousepad extra grande de superficie lisa, ideal para setup completo",
    image: "productos para testing/MP830.jpg",
    stock: 20,
  },
  {
    id: 19,
    sku: "MP845",
    name: "Mousepad XL 70 x 30 x 3 cm - Colores - Negro Havit",
    category: "Mousepads",
    price: 3999,
    description: "Mousepad XL con diseño colorido sobre base negra",
    image: "productos para testing/MP845.jpg",
    stock: 20,
  },
  {
    id: 20,
    sku: "MP860",
    name: "Mousepad Gamer XL 70x30cm Havit",
    category: "Mousepads",
    price: 3999,
    description: "Mousepad gamer XL con superficie optimizada para gaming",
    image: "productos para testing/MP860.jpg",
    stock: 20,
  },
  {
    id: 21,
    sku: "MP861",
    name: "Mousepad Gamer XL 70x30cm Havit",
    category: "Mousepads",
    price: 3999,
    description: "Mousepad gamer XL con diseño alternativo y excelente deslizamiento",
    image: "productos para testing/MP861.jpg",
    stock: 20,
  },

  // Mouses
  {
    id: 22,
    sku: "MS1001S",
    name: "Mouse Gamer RGB 4800dpi Havit",
    category: "Mouses",
    price: 5999,
    description: "Mouse gamer con iluminación RGB y sensor de hasta 4800 DPI",
    image: "productos para testing/MS1001S.jpg",
    stock: 40,
  },
  {
    id: 23,
    sku: "MS1010",
    name: "Mouse Gamer RGB 3600dpi Havit",
    category: "Mouses",
    price: 4999,
    description: "Mouse gamer con iluminación RGB y sensor de 3600 DPI",
    image: "productos para testing/MS1010.jpg",
    stock: 60,
  },
  {
    id: 24,
    sku: "MS1020WB",
    name: "Mouse Gamer Inalámbrico - Blanco Havit",
    category: "Mouses",
    price: 8999,
    description: "Mouse gamer inalámbrico en elegante color blanco",
    image: "productos para testing/MS1020WB.jpg",
    stock: 40,
  },
  {
    id: 25,
    sku: "MS1020N",
    name: "Mouse Gamer Inalámbrico - Negro Havit",
    category: "Mouses",
    price: 8999,
    description: "Mouse gamer inalámbrico en clásico color negro",
    image: "productos para testing/MS1020N.jpg",
    stock: 40,
  },
  {
    id: 26,
    sku: "MS1027",
    name: "Mouse Gaming 6 botones 3600 dpi RGB Havit",
    category: "Mouses",
    price: 5499,
    description: "Mouse gaming con 6 botones programables, 3600 DPI y RGB",
    image: "productos para testing/MS1027.jpg",
    stock: 60,
  },
  {
    id: 27,
    sku: "MS1029",
    name: "Mouse Gamer RGB 7200dpi Havit",
    category: "Mouses",
    price: 6999,
    description: "Mouse gamer de alta precisión con sensor de 7200 DPI y RGB",
    image: "productos para testing/MS1029.jpg",
    stock: 60,
  },
  {
    id: 28,
    sku: "MS966WB",
    name: "Mouse Gamer Inalámbrico 7 Botones 10000 dpi RGB - Negro Havit",
    category: "Mouses",
    price: 11999,
    description: "Mouse gamer inalámbrico premium con 7 botones y sensor de 10000 DPI",
    image: "productos para testing/MS966WB.jpg",
    stock: 40,
  },
  {
    id: 29,
    sku: "MS969SE",
    name: "Mouse Gamer Inalámbrico - Negro Havit",
    category: "Mouses",
    price: 9999,
    description: "Mouse gamer inalámbrico con diseño ergonómico y tecnología avanzada",
    image: "productos para testing/MS969SE.jpg",
    stock: 40,
  },

  // Proyectores
  {
    id: 30,
    sku: "PJ209A-PRO-EU",
    name: "Proyector 8500 lumens 450 ansi - Havit",
    category: "Proyectores",
    price: 89999,
    description: "Proyector profesional de alta luminosidad con 8500 lúmenes y 450 ANSI",
    image: "productos para testing/PJ209A-PRO-EU.jpg",
    stock: 6,
  },
  {
    id: 31,
    sku: "PJ217",
    name: "Proyector 720p 7500 lumens 180 ANSI lumens - Blanco Havit",
    category: "Proyectores",
    price: 69999,
    description: "Proyector HD 720p con 7500 lúmenes y 180 ANSI en color blanco",
    image: "productos para testing/PJ217.jpg",
    stock: 12,
  },

  // Parlantes
  {
    id: 32,
    sku: "SK215",
    name: "Barra de sonido bluetooth - Negro Ocre Havit",
    category: "Parlantes",
    price: 12999,
    description: "Barra de sonido Bluetooth con diseño elegante en negro y ocre",
    image: "productos para testing/SK215.jpg",
    stock: 20,
  },
  {
    id: 33,
    sku: "SK216",
    name: "Parlante Gaming Escritorio usb.2.0 2x5w - Havit",
    category: "Parlantes",
    price: 7999,
    description: "Parlantes gaming para escritorio con conexión USB 2.0 y potencia 2x5W",
    image: "productos para testing/SK216.jpg",
    stock: 20,
  },
  {
    id: 34,
    sku: "SK770BT",
    name: "Barra sonido bluetooth 5.3 2x5w - Havit",
    category: "Parlantes",
    price: 11999,
    description: "Barra de sonido con Bluetooth 5.3 y potencia 2x5W",
    image: "productos para testing/SK770BT.jpg",
    stock: 12,
  },
  {
    id: 35,
    sku: "SK801A",
    name: "Parlante Portatil Bluetooth TF Jack 3.5mm - Azul Havit",
    category: "Parlantes",
    price: 5999,
    description: "Parlante portátil Bluetooth con ranura TF y jack 3.5mm en azul",
    image: "productos para testing/SK801A.jpg",
    stock: 40,
  },
  {
    id: 36,
    sku: "SK801N",
    name: "Parlante Portatil Bluetooth TF Jack 3.5mm - Negro Havit",
    category: "Parlantes",
    price: 5999,
    description: "Parlante portátil Bluetooth con ranura TF y jack 3.5mm en negro",
    image: "productos para testing/SK801N.jpg",
    stock: 40,
  },
  {
    id: 37,
    sku: "SK809BT",
    name: "Parlante Bluetooth USB AUX SD FM - Negro Havit",
    category: "Parlantes",
    price: 6999,
    description: "Parlante Bluetooth multifunción con USB, AUX, SD y radio FM",
    image: "productos para testing/SK809BT.jpg",
    stock: 40,
  },
  {
    id: 38,
    sku: "SK874BT",
    name: "Parlante bluetooth Usb Aux Sd FM - Negro Havit",
    category: "Parlantes",
    price: 7999,
    description: "Parlante Bluetooth con múltiples opciones de conectividad",
    image: "productos para testing/SK874BT.jpg",
    stock: 40,
  },
  {
    id: 39,
    sku: "SK903BT",
    name: "Parlante bluetooth Colgante AUX SD - Negro Havit",
    category: "Parlantes",
    price: 8999,
    description: "Parlante Bluetooth colgante con AUX y ranura SD",
    image: "productos para testing/SK903BT.jpg",
    stock: 6,
  },

  // Accesorios
  {
    id: 40,
    sku: "HN11P",
    name: "Webcam usb 2.0 1080p 2 mpx - Havit",
    category: "Accesorios",
    price: 9999,
    description: "Webcam Full HD 1080p con sensor de 2 megapíxeles y conexión USB 2.0",
    image: "productos para testing/HN11P.jpg",
    stock: 40,
  },
  {
    id: 41,
    sku: "ST7012PRO",
    name: "Aro Led Con Tripode - Havit",
    category: "Accesorios",
    price: 14999,
    description: "Aro de luz LED profesional con trípode incluido para streaming y fotografía",
    image: "productos para testing/ST7012PRO.jpg",
    stock: 15,
  },
  {
    id: 42,
    sku: "EM1601",
    name: "Masajeador de ojos - Smart life - Gris Havit",
    category: "Accesorios",
    price: 19999,
    description: "Masajeador de ojos inteligente para aliviar la fatiga visual",
    image: "productos para testing/EM1601.jpg",
    stock: 12,
  },
  {
    id: 43,
    sku: "F2005",
    name: "Cooler CPU Refrigeración por Aire - RGB - Havit",
    category: "Accesorios",
    price: 16999,
    description: "Cooler para CPU con refrigeración por aire e iluminación RGB",
    image: "productos para testing/F2005.jpg",
    stock: 20,
  },
  {
    id: 44,
    sku: "HV-F2035",
    name: 'Base Para Notebook 15.6" - 2 coolers - Havit',
    category: "Accesorios",
    price: 8999,
    description: "Base refrigeradora para notebook de hasta 15.6 pulgadas con 2 coolers",
    image: "productos para testing/HV-F2035.jpg",
    stock: 20,
  },
  {
    id: 45,
    sku: "F2095",
    name: "Cooler Fan RGB - Havit",
    category: "Accesorios",
    price: 4999,
    description: "Ventilador RGB para gabinete con iluminación personalizable",
    image: "productos para testing/F2095.jpg",
    stock: 40,
  },
  {
    id: 46,
    sku: "G158BT-Pro",
    name: "Joystick Bluetooth Con Soporte P/Celular - Negro Havit",
    category: "Accesorios",
    price: 13999,
    description: "Joystick Bluetooth con soporte integrado para celular, ideal para gaming móvil",
    image: "productos para testing/G158BT-Pro.jpg",
    stock: 20,
  },
  {
    id: 47,
    sku: "GK50-Pro",
    name: "Microfono Gaming Havit",
    category: "Accesorios",
    price: 18999,
    description: "Micrófono gaming profesional con excelente calidad de audio",
    image: "productos para testing/GK50-Pro.jpg",
    stock: 10,
  },
  {
    id: 48,
    sku: "GK61",
    name: "Microfono Gaming Havit",
    category: "Accesorios",
    price: 16999,
    description: "Micrófono gaming con diseño compacto y gran calidad de sonido",
    image: "productos para testing/GK61.jpg",
    stock: 20,
  },
  {
    id: 49,
    sku: "ADG-001",
    name: "Aire Comprimido GTC",
    category: "Accesorios",
    price: 2999,
    description: "Aire comprimido para limpieza de equipos electrónicos y periféricos",
    image: "productos para testing/ADG-001.jpg",
    stock: 24,
  },
  {
    id: 50,
    sku: "CABLE-HDMI",
    name: "Cable HDMI 2.0 Premium 2m - Havit",
    category: "Accesorios",
    price: 3499,
    description: "Cable HDMI 2.0 de alta velocidad, soporta 4K a 60Hz",
    image: "productos para testing/CABLE-HDMI.jpg",
    stock: 50,
  },
]

window.productsData = productsData
